name: Update Google Scholar Badge

on:
  push:
    branches:
      - main       # 或者你想要的其他分支
  schedule:
    - cron: '0 0 * * *'    # 保留原有的定时
  workflow_dispatch:      # 手动触发仍然可用

permissions:
  contents: write

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install deps
        run: pip install google-search-results requests cairosvg

      - name: Generate badge SVG
        env:
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
        run: python update_scholar_badge.py

      - name: Debug – list files & git status
        run: |
          echo "工作目录：$(pwd)"
          ls -al .
          git status

      - name: Commit & Push badge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f scholar_badge.svg
          git commit -m "chore: update Google Scholar badge" || echo "No changes to commit"
          git push origin main