name: Update Google Scholar Badge

on:
  push:
    branches:
      - main       # 或者你想要的其他分支
  schedule:
    - cron: '0 0 * * *'    # 保留原有的定时
  workflow_dispatch:      # 手动触发仍然可用

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install google-search-results requests

      - name: Generate badge SVG
        env:
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
        run: python update_scholar_badge.py

      - name: Commit & Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "你的用户名"
          git config user.email "你的邮箱"
          git add scholar_badge.svg
          git diff --quiet || git commit -m "chore: update Google Scholar badge"
          git push
