name: Update Google Scholar Badge

on:
  schedule:
    - cron: '0 0 * * *'   # 每天 UTC 00:00 更新一次
  workflow_dispatch:     # 允许手动触发

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install google-search-results requests

      - name: Generate badge SVG
        env:
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
        run: python update_scholar_badge.py

      - name: Commit & Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add scholar_badge.svg
          git diff --quiet || git commit -m "chore: update Google Scholar badge"
          git push
